# Generated by Django 6.0.3 on 2026-03-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
