# Generated by Django 6.0.3 on 2026-03-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_voucher'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='voucher_code',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.voucher'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='voucher.plan'),
        ),
    ]
