# Generated by Django 6.0.3 on 2026-04-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_phone'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('code', 'plan'), name='unique_code_per_plan'),
        ),
    ]
