# Generated by Django 6.0.3 on 2026-04-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_voucher_unique_code_per_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
