# Generated by Django 6.0.3 on 2026-04-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mlm_active',
            field=models.BooleanField(default=True),
        ),
    ]
