# Generated by Django 6.0.3 on 2026-04-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_is_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_processed',
            field=models.BooleanField(default=False),
        ),
    ]
