# Generated by Django 6.0.3 on 2026-04-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_commission_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
