# Generated by Django 6.0.3 on 2026-03-27 04:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_passiveincome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passiveincome',
            unique_together={('user', 'month_number')},
        ),
    ]
