# Generated by Django 6.0.3 on 2026-04-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transaction_related_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levelcommission',
            options={'ordering': ['level']},
        ),
        migrations.AlterField(
            model_name='levelcommission',
            name='level',
            field=models.IntegerField(unique=True),
        ),
    ]
