# Generated by Django 6.0.3 on 2026-04-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='passiveincome',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
