# Generated by Django 6.0.3 on 2026-04-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_pendinglevelcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='passiveincome',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
