# Generated by Django 6.0.3 on 2026-04-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_passiveincome_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
